---
title: "Second Method"
output: html_document
---
```{r, echo=TRUE}

#### Data preparation ####
library(dplyr)
library(tidyr)
library(rpart)
library(randomForest)
library(ggplot2)
library(gbm)

df <- read.csv("~/Desktop/train.csv", stringsAsFactors = F)
row.names(df) <- df$Id
df <- df[,-1]
df[is.na(df)] <- 0
for(i in colnames(df[,sapply(df, is.character)])){
    df[,i] <- as.factor(df[,i])
}

test.n <- sample(1:nrow(df), nrow(df)/3, replace = F)
test <- df[test.n,]
train <- df[-test.n,]

RMSE <- function(x,y){
    a <- sqrt(sum((log(x)-log(y))^2)/length(y))
    return(a)
}


#### Regression Trees, "anova" ####
model1 <- rpart(SalePrice ~., data = train, method = "anova")
predict1 <- predict(model1, test)
RMSE1 <- RMSE(predict1, test$SalePrice)
RMSE1 <- round(RMSE1, digits = 3)
plot1 <- predict1-test$SalePrice
RMSE1 


#### Random Forests, "anova" ####
model2 <- randomForest(SalePrice ~., data = train, method = "anova",
                      ntree = 300,
                      mtry = 26,
                      replace = F,
                      nodesize = 1,
                      importance = T)
predict2 <- predict(model2, test)
RMSE2 <- RMSE(predict2, test$SalePrice)
RMSE2 <- round(RMSE2, digits = 3)
plot2 <- predict2-test$SalePrice
RMSE2 

### BestPredForest.csv
BestPredForest <- data.frame(Id= test.n, PredSalePrice= predict2, SalePrice= test$SalePrice)
write.csv(BestPredForest, "BestPredForest.csv")


### Plot: "Difference between predict and real values" 
data_plot <- data.frame("regression trees" = plot1,
                        "random forests" = plot2)
data_plot$Id <- row.names(data_plot)
data_plot <- gather(data_plot, method, value, - Id)
data_plot$method <- as.factor(data_plot$method)
levels(data_plot$method) <- c(paste0("Random Forests (", RMSE2, ")"),
                              paste0("Regression Trees (", RMSE1, ")"))

ggplot(data_plot, aes(x = Id, y = value, colour = method))+
    geom_point(alpha = 0.7, size = 2)+
    ggtitle("The difference between predict and real prices")+
    labs(x = "Buyer Id", y = "The difference between prices", colour = " ")+
    scale_x_discrete(breaks = c(0))+
    theme(legend.position = "top",
          legend.text = element_text(size = 12),
          axis.text.x = element_blank(), 
          axis.title.x = element_text(size = 14),
          axis.text.y = element_text(size = 14), 
          axis.title.y = element_text(size = 14),
          title = element_text(size = 16))

```


```{r, echo=TRUE}
library(ggplot2) 
library(readr) 
library(Hmisc)
library("caret")
library("rpart")
library("tree")
library("randomForest")
library("e1071")

# Impute raw data 
train <- read.csv("~/Desktop/train.csv",header = T, na.strings= "NA")
SalePrice = train$SalePrice
test <- read.csv("~/Desktop/test.csv",header = T, na.strings= "NA")
df <- rbind(train[,!(names(train) %in% c("SalePrice"))],test)
print(sum(is.na(df)))
df$YearBuilt<-as.factor(df$YearBuilt)
df$YearRemodAdd<-as.factor(df$YearRemodAdd)
df$MSSubClass<-as.factor(df$MSSubClass)
df$OverallQual<-as.factor(df$OverallQual)
df$OverallCond<-as.factor(df$OverallCond)
df$MoSold<-as.factor(df$MoSold)
df$YrSold<-as.factor(df$YrSold)
df$GarageYrBlt<-as.factor(df$GarageYrBlt)

# Imputing missing data
dfClean <-function(df){
  # Pool Variable: If PoolQC = NA and PoolArea = 0 , assign factor NoPool
  df$PoolQC <- as.character(df$PoolQC)
  df$PoolQC[df$PoolArea %in% c(0,NA) & is.na(df$PoolQC)] <- "NoPool"
  df$PoolQC <- as.factor(df$PoolQC)
  # MiscFeature Variable: If MiscFeature = NA and MiscVal = 0, assign factor None
  df$MiscFeature <- as.character(df$MiscFeature)
  df$MiscFeature[df$MiscVal %in% c(0,NA) & is.na(df$MiscFeature)] <- "None"
  df$MiscFeature <- as.factor(df$MiscFeature)
  # Alley Variable: If Alley = NA, assign factor NoAccess
  df$Alley <- as.character(df$Alley)
  df$Alley[is.na(df$Alley)] <- "NoAccess"
  df$Alley <- as.factor(df$Alley)
  # Fence Variable: If Fence = NA, assign factor NoFence
  df$Fence <- as.character(df$Fence)
  df$Fence[is.na(df$Fence)] <- "NoFence"
  df$Fence <- as.factor(df$Fence)
  # FireplaceQu Variable: If FireplaceQu = NA and Fireplaces = 0 , assign factor NoFirePlace
  df$FireplaceQu <- as.character(df$FireplaceQu)
  df$FireplaceQu[df$Fireplaces %in% c(0,NA) & is.na(df$FireplaceQu)] <- "NoFirePlace"
  df$FireplaceQu <- as.factor(df$FireplaceQu)
  # GarageYrBlt Variable: If GarageYrBlt = NA and GarageArea = 0 assign factor NoGarage
  df$GarageYrBlt <- as.character(df$GarageYrBlt)
  df$GarageYrBlt[df$GarageArea %in% c(0,NA) & is.na(df$GarageYrBlt)] <- "NoGarage"
  df$GarageYrBlt <- as.factor(df$GarageYrBlt)
  # GarageFinish Variable: If GarageFinish = NA and GarageArea = 0 assign factor NoGarage
  df$GarageFinish <- as.character(df$GarageFinish)
  df$GarageFinish[df$GarageArea %in% c(0,NA) & is.na(df$GarageFinish)] <- "NoGarage"
  df$GarageFinish <- as.factor(df$GarageFinish)
  # GarageQual Variable: If GarageQual = NA and GarageArea = 0 assign factor NoGarage
  df$GarageQual <- as.character(df$GarageQual)
  df$GarageQual[df$GarageArea %in% c(0,NA) & is.na(df$GarageQual)] <- "NoGarage"
  df$GarageQual <- as.factor(df$GarageQual)
  # GarageCond Variable: If GarageCond = NA and GarageArea = 0 assign factor NoGarage
  df$GarageCond <- as.character(df$GarageCond)
  df$GarageCond[df$GarageArea %in% c(0,NA) & is.na(df$GarageCond)] <- "NoGarage"
  df$GarageCond <- as.factor(df$GarageCond)
  # GarageType Variable: If GarageType = NA and GarageArea = 0 assign factor NoGarage
  df$GarageType <- as.character(df$GarageType)
  df$GarageType[df$GarageArea %in% c(0,NA) & is.na(df$GarageType)] <- "NoGarage"
  df$GarageType <- as.factor(df$GarageType)

  df$GarageArea[is.na(df$GarageArea) & df$GarageCars %in% c(0,NA)] <- 0
  df$GarageCars[is.na(df$GarageCars) & df$GarageArea %in% c(0,NA)] <- 0


  # BsmtFullBath Variable: If BsmtFullBath = NA and TotalBsmtSF = 0 assign 0
  df$BsmtFullBath[df$TotalBsmtSF %in% c(0,NA) & is.na(df$BsmtFullBath)] <- 0
  # BsmtHalfBath Variable: If BsmtHalfBath = NA and TotalBsmtSF = 0 assign 0
  df$BsmtHalfBath[df$TotalBsmtSF %in% c(0,NA) & is.na(df$BsmtHalfBath)] <- 0

  # BsmtFinSF1 Variable: If BsmtFinSF1 = NA and TotalBsmtSF = 0 assign 0
  df$BsmtFinSF1[df$TotalBsmtSF %in% c(0,NA) & is.na(df$BsmtFinSF1)] <- 0
  # BsmtFinSF2 Variable: If BsmtFinSF2 = NA and TotalBsmtSF = 0 assign 0
  df$BsmtFinSF2[df$TotalBsmtSF %in% c(0,NA) & is.na(df$BsmtFinSF2)] <- 0
  # BsmtUnfSF Variable: If BsmtUnfSF = NA and TotalBsmtSF = 0 assign 0
  df$BsmtUnfSF[df$TotalBsmtSF %in% c(0,NA) & is.na(df$BsmtUnfSF)] <- 0
  # TotalBsmtSF Variable: If TotalBsmtSF = NA and TotalBsmtSF = 0 assign 0
  df$TotalBsmtSF[df$TotalBsmtSF %in% c(0,NA) & is.na(df$TotalBsmtSF)] <- 0

  # BsmtQual Variable: If BsmtQual = NA and TotalBsmtSF = 0 assign factor NoBasement
  df$BsmtQual <- as.character(df$BsmtQual)
  df$BsmtQual[df$TotalBsmtSF %in% c(0,NA) & is.na(df$BsmtQual)] <- "NoBasement"
  df$BsmtQual <- as.factor(df$BsmtQual)
  # BsmtFinType1 Variable: If BsmtFinType1 = NA and TotalBsmtSF = 0 assign factor NoBasement
  df$BsmtFinType1 <- as.character(df$BsmtFinType1)
  df$BsmtFinType1[df$TotalBsmtSF %in% c(0,NA) & is.na(df$BsmtFinType1)] <- "NoBasement"
  df$BsmtFinType1 <- as.factor(df$BsmtFinType1)
  # BsmtFinType2 Variable: If BsmtFinType2 = NA and TotalBsmtSF = 0 assign factor NoBasement
  df$BsmtFinType2 <- as.character(df$BsmtFinType2)
  df$BsmtFinType2[df$TotalBsmtSF %in% c(0,NA) & is.na(df$BsmtFinType2)] <- "NoBasement"
  df$BsmtFinType2 <- as.factor(df$BsmtFinType2)
  # BsmtExposure Variable: If BsmtExposure = NA and TotalBsmtSF = 0 assign factor NoBasement
  df$BsmtExposure <- as.character(df$BsmtExposure)
  df$BsmtExposure[df$TotalBsmtSF %in% c(0,NA) & is.na(df$BsmtExposure)] <- "NoBasement"
  df$BsmtExposure <- as.factor(df$BsmtExposure)
  # BsmtCond Variable: If BsmtCond = NA and TotalBsmtSF = 0 assign factor NoBasement
  df$BsmtCond <- as.character(df$BsmtCond)
  df$BsmtCond[df$TotalBsmtSF %in% c(0,NA) & is.na(df$BsmtCond)] <- "NoBasement"
  df$BsmtCond <- as.factor(df$BsmtCond)
  return(df)
}
df <- dfClean(df)

# Additional cleaning: MasVnrType, MasVnrArea
df$MasVnrType <- as.character(df$MasVnrType)
df$MasVnrType[is.na(df$MasVnrType)] <- "None"
df$MasVnrType <- as.factor(df$MasVnrType)
df$MasVnrArea[is.na(df$MasVnrArea)] <- 0

# MSZoning
df$MSZoning <- as.character(df$MSZoning)
df$MSZoning[is.na(df$MSZoning)] <- "RL"
df$MSZoning <- as.factor(df$MSZoning)

# BsmtExposure
df$BsmtExposure <- as.character(df$BsmtExposure)
df$BsmtExposure[is.na(df$BsmtExposure)]<-"No"
df$BsmtExposure <- as.factor(df$BsmtExposure)

# BsmtFinType2
df$BsmtFinType2 <- as.character(df$BsmtFinType2)
df$BsmtFinType2[is.na(df$BsmtFinType2)]<-"ALQ"
df$BsmtFinType2 <- as.factor(df$BsmtFinType2)

# BsmtQual
df$BsmtQual <- as.character(df$BsmtQual)
df$BsmtQual[is.na(df$BsmtQual) & df$HouseStyle == "2Story"]<-"Gd"
df$BsmtQual[is.na(df$BsmtQual) & df$HouseStyle == "1.5Fin"]<-"TA"
df$BsmtQual <- as.factor(df$BsmtQual)

# BsmtCond
df$BsmtCond <- as.character(df$BsmtCond)
df$BsmtCond[is.na(df$BsmtCond)]<-"TA"
df$BsmtCond <- as.factor(df$BsmtCond)

# Replace all the other numerical values with the mode
fillMiss<- function(x){
  ux <- unique(x[!is.na(x)])
  x <- as.character(x)
  mode <- ux[which.max(tabulate(match(x[!is.na(x)], ux)))]
  x[is.na(x)] <- as.character(mode)
  x <- as.factor(x)
  return(x)
}
df[,sapply(df,function(x){!(is.numeric(x))}) ]<-as.data.frame(apply(df[,sapply(df,function(x){!(is.numeric(x))}) ],2,fillMiss))

# Set LotFrontage where it is not defined to sqrt(LotArea)
df$LotFrontage[is.na(df$LotFrontage)]=sqrt(df$LotArea)[is.na(df$LotFrontage)]

# Finally get the training data back and transform
myData=df[1:nrow(train),]
myData$SalePrice=log(train$SalePrice)
myData$LotArea=sqrt(myData$LotArea)
myData$MasVnrArea=sqrt(myData$MasVnrArea)

# Break into traindata and testdata
ntrain=round(nrow(myData)*0.75)
train.id=sample(1:nrow(myData), ntrain)
traindata=myData[train.id,]
testdata=myData[-train.id,]
RMSE <- function(x,y){
    a <- sqrt(sum((log(x)-log(y))^2)/length(y))
    return(a)
}

####Ridge####
### Convert any qualitative variables to dummy variables
x=model.matrix(SalePrice~.,myData)[,-1] # toss out intercept column
y=myData$SalePrice

### Split the dataset into training and testing
train = sample(1:nrow(x), nrow(x)/2)
test = -train

training_x = x[train,]
testing_x = x[test,]

training_y = y[train]
testing_y = y[test]

library(glmnet)
grid = 10^seq (10,-2,length =100)
ridge_model = glmnet(training_x,training_y,alpha = 0,lambda = grid, standardize = FALSE)
dim(coef(ridge_model))

plot(ridge_model, xvar = "lambda", label = TRUE)

### Best Lambda
cv_error = cv.glmnet(training_x, 
                     training_y, 
                     alpha = 0) #default 10 fold cv
plot(cv_error) # cross-validation curve (red dotted line), upper and lower standard deviation curves 

best_lambda = cv_error$lambda.min
best_lambda

### Model with Best Lambda
model_coef = predict(ridge_model, 
                     type = "coefficients",
                     s= best_lambda)

### Test the Model 
predicted_y = predict(ridge_model, 
                      s= best_lambda,
                      newx = testing_x)
### RMSE
RMSE_RIDGE=RMSE(predicted_y, testing_y)
RMSE_RIDGE 

### BestPredRIDGE.csv
BestPredRIDGE <- data.frame(Id = testdata$Id, PredSalePrice= predicted_y, SalePrice= testing_y)
write.csv(BestPredRIDGE, "BestPredRIDGE.csv")

####LASSO####
### Convert any qualitative variables to dummy variables
x=model.matrix(SalePrice~.,myData)[,-1] # get rid of intercept column
y=myData$SalePrice

### Split the dataset into training and testing
train = sample(1:nrow(x), nrow(x)/2)
test = -train

training_x = x[train,]
testing_x = x[test,]

training_y = y[train]
testing_y = y[test]

library(glmnet)
grid = 10^seq (10,-2,length =100)

lasso_model = glmnet(training_x, 
                     training_y, 
                     alpha =1,
                     lambda=grid,
                     standardize=FALSE)

plot(lasso_model, xvar = "lambda",label = TRUE)

cv_error = cv.glmnet(training_x, 
                     training_y, 
                     alpha = 1)
best_lambda = cv_error$lambda.min
best_lambda 

plot(cv_error)

### OUR FINAL LASSO 
model_coef = predict(lasso_model, 
                     type = "coefficients",
                     s= best_lambda)

### Test the Model 
predicted_yL = predict(lasso_model, 
                      s= best_lambda,
                      newx = testing_x)
### RMSE
RMSE_LASSO<- RMSE(predicted_yL, testing_y)
RMSE_LASSO 

### BestPredLASSO.csv
BestPredLASSO <- data.frame(Id = testdata$Id, PredSalePrice= predicted_yL, SalePrice= testing_y)
write.csv(BestPredLASSO, "BestPredLASSO.csv")
```
